### ISSUE TITLE
DBReader oracle exception handling

### ISSUE THREAD

**Issue by ghost** [intelie/pycollector#47]
Improve exception handling following these considerations:
http://stackoverflow.com/questions/7465889/cx-oracle-and-exception-handling-good-practices

**Comment by ghost** [comment]
It is important to handle this kind of exception:

2012-08-24 07:42:06,534 - DBReader.py (58) [(Thread-2347)] ERROR - Traceback (most recent call last):
  File "/opt/intelie/pycollector/lib/rwtypes/readers/db/DBReader.py", line 50, in do_query
    self.results = self.session.query(_self.columns).from_statement(self.query).all()
  File "/opt/intelie/pycollector/lib/third/sqlalchemy/orm/query.py", line 1947, in all
    return list(self)
  File "/opt/intelie/pycollector/lib/third/sqlalchemy/orm/query.py", line 2057, in **iter**
    return self._execute_and_instances(context)
  File "/opt/intelie/pycollector/lib/third/sqlalchemy/orm/query.py", line 2070, in _execute_and_instances
    close_with_result=True)
  File "/opt/intelie/pycollector/lib/third/sqlalchemy/orm/query.py", line 2061, in _connection_from_session
    *_kw)
  File "/opt/intelie/pycollector/lib/third/sqlalchemy/orm/session.py", line 719, in connection
    close_with_result=close_with_result)
  File "/opt/intelie/pycollector/lib/third/sqlalchemy/orm/session.py", line 723, in _connection_for_bind
    return self.transaction._connection_for_bind(engine)
  File "/opt/intelie/pycollector/lib/third/sqlalchemy/orm/session.py", line 266, in _connection_for_bind
    conn = bind.contextual_connect()
  File "/opt/intelie/pycollector/lib/third/sqlalchemy/engine/base.py", line 2340, in contextual_connect
    self.pool.connect(),
  File "/opt/intelie/pycollector/lib/third/sqlalchemy/pool.py", line 210, in connect
    return _ConnectionFairy(self).checkout()
  File "/opt/intelie/pycollector/lib/third/sqlalchemy/pool.py", line 371, in __init__
    rec = self._connection_record = pool._do_get()
  File "/opt/intelie/pycollector/lib/third/sqlalchemy/pool.py", line 697, in _do_get
    con = self._create_connection()
  File "/opt/intelie/pycollector/lib/third/sqlalchemy/pool.py", line 174, in _create_connection
    return _ConnectionRecord(self)
  File "/opt/intelie/pycollector/lib/third/sqlalchemy/pool.py", line 256, in __init__
    self.connection = self.__connect()
  File "/opt/intelie/pycollector/lib/third/sqlalchemy/pool.py", line 316, in __connect
    connection = self.__pool._creator()
  File "/opt/intelie/pycollector/lib/third/sqlalchemy/engine/strategies.py", line 80, in connect
    return dialect.connect(_cargs, *_cparams)
  File "/opt/intelie/pycollector/lib/third/sqlalchemy/engine/default.py", line 280, in connect
    return self.dbapi.connect(_cargs, *_cparams)
DatabaseError: (DatabaseError) ORA-12549: TNS:operating system resource quota exceeded
 None None

After restarting the daemon, this exception stops ocurring.

**Comment by ghost** [comment]
Other related problem is that the reader keeps "busy" forever:

2012-08-30 21:50:07,313 - __reader.py (196) [(Thread-325)] DEBUG - Reader is busy with other reading. Skipping this scheduling.

Again, the restart solves the problem.
