### ISSUE TITLE
Bug: error reading checkpoint

### ISSUE THREAD

**Issue by ghost** [intelie/pycollector#53]
2012-06-27 14:15:07,308 - __writer.py (161) [(MainThread)] ERROR - Error reading checkpoint in /data/iem/checkpoint/pd/AZ.0001a.writer.
2012-06-27 14:15:07,309 - __writer.py (162) [(MainThread)] ERROR - It may be the case to remove it manually.
2012-06-27 14:15:07,309 - __writer.py (163) [(MainThread)] ERROR - Traceback (most recent call last):
  File "/usr/local/pycollector/lib/__writer.py", line 151, in _read_checkpoint
    read = pickle.load(f)
  File "/usr/lib64/python2.6/pickle.py", line 1370, in load
    return Unpickler(file).load()
  File "/usr/lib64/python2.6/pickle.py", line 858, in load
    dispatch[key](self)
  File "/usr/lib64/python2.6/pickle.py", line 966, in load_string
    raise ValueError, "insecure string pickle"
ValueError: insecure string pickle

**Comment by ghost** [comment]
A corrupted pickle. The error is raised if a string in the dump does not both start and end with " or '.
http://stackoverflow.com/questions/1746825/python-valueerror-insecure-string-pickle

**Comment by ghost** [comment]
created new writer option "remove_corrupted_checkpoint_file" to automatically remove the writer checkpoint file if it is corrupted.
